version: '3.8'

services:
    web:
        build: .
        container_name: school_mng_web
        ports:
            - '3000:3000'
        environment:
            - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
        volumes:
            - .:/code
        depends_on:
            - db
    db:
        image: postgres:15
        container_name: postgres_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydb

volumes:
    postgres_data:
